Antes de entregar el challenge, comprueba que todo funciona como esperas. Para ello reinicia el kernel y ejecuta el notebook desde el principio: (Kernel$\rightarrow$Restart) y luego **run all cells** (en el menu, selecciona Cell$\rightarrow$Run All).

**Recuerda que es muy importante que guardes el worksheet con el nombre correcto**: `<nombre y apellido sin espacio>_solution_<titulo del notebook>`.

Por ejemplo, para un notebook `pf2_python_basics_ch.ipynb`, la forma en que yo debo entregarlo es: 

`mariolopez_solution_pf2_python_basics_ch.ipynb`

Completa todos los lugares que contienen `YOUR CODE HERE` o "YOUR ANSWER HERE", y tu nombre en `NAME`.

In [1]:
NAME = "Alberto Camacho"

<img src="mioti.png" style="height: 100px">
<center style="color:#888">Data Science with Python @ Data Science for IoT</center>

# DSPy5. NumPy Challenge

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#A-bit-more-of-slicing-(0.3p)" data-toc-modified-id="A-bit-more-of-slicing-(0.3p)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>A bit more of slicing (0.3p)</a></span></li><li><span><a href="#Broadcasting-into-practice:-feature-scaling-through-standarization-(1p)" data-toc-modified-id="Broadcasting-into-practice:-feature-scaling-through-standarization-(1p)-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Broadcasting into practice: feature scaling through standarization (1p)</a></span></li><li><span><a href="#Sistemas-de-coordenadas---Vectorización-(0.7p)" data-toc-modified-id="Sistemas-de-coordenadas---Vectorización-(0.7p)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Sistemas de coordenadas - Vectorización (0.7p)</a></span></li></ul></div>

## A bit more of slicing (0.3p)

* Crea una matriz tamaño n x m de todo ceros, rodeada de 1s. 

In [2]:
n = 4
m = 9
# YOUR CODE HERE
import numpy as np
#Primero se convierte el array de unos para preparar el contorno
array_ones = np.ones((4,9))
#Se selecciona el rango con el slice de las posiciones centrales y se asigna el valor 0
array_ones[1:3 , 1:8] = 0
#Se convierte el tipo del array a entero
array_ones = array_ones.astype(int)
#Imprimir output
array_ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

* Crea una matriz con patrón de tablero de ajedrez. Las casillas negras serán 0, las blancas 1.
<img src="chess.png" style="height: 300px">


In [3]:
# se crean diferentes matrices cuyas diagonales principales son unos y el resto ceros; usando np.eye() 
#la primera, "table", será 8x8 para representar la tabla entera. A partir de ahí se crean  sub-matrices de
# 4x4, 2x2 y 6x6 para combinarlas con "table", y tener las posiciones blancas como diagonales de "1".
table = np.eye(8)
mount = np.eye(4)
mount_2 = np.eye(2)
mount_final = np.eye(6)

#En primer lugar igualmos las matrices 4x4 y 2x2 a los sub-elementos de table que tiene que combinarse para tener 
#las posiciones blancas como unos.
table[4:8 , 0:4] = mount
table[0:4 , 4:8] = mount
table [0:2, 6:8] = mount_2
table [6:8, 0:2] = mount_2

#Finalmente nos quedan las casillas blancas en forma de diagonal de 6. Se suman y no igualan en este caso para no 
#modificar los cambios previos y cambiar "1" por "0"
table [2:8, 0:6] = table [2:8, 0:6] + mount_final
table [0:6, 2:8] = table [0:6, 2:8] + mount_final
table_final = table.astype(int)

table_final

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## Broadcasting into practice: feature scaling through standarization (1p)

Con algunas excepciones, los algoritmos de Machine Learning no funcionan del todo bien si los atributos numéricos que se les pasan tienen escalas muy diferentes ([further reading](http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html)). Una técnica que puede usarse para que todos los atributos tengan la misma escala es la estandarización: sustraerles la media (para que sea 0) y dividirlos por la desviación típica (de modo que la varianza resultante sea 1). 

a) Imaginemos que tenemos un array con datos de un sensor en una playa, que mide cuatro atributos como serían calidad del agua, viento, oleaje y temperatura, en distintas unidades que tienen distintas escalas. Esas mediciones nos llegan en un array con 3 columnas (una por feature) y 1000 filas (una fila por cada instante de tiempo del que tenemos las medidas). 

In [4]:
data = np.random.normal(loc=[-10, 0, 10], scale=[2, 1, 2], size=(1000,3))
data.shape

(1000, 3)

Estandariza esa matriz de manera vectorial: réstale la media por columna y divide por la desviación típica de cada columna.

In [5]:
#Array final = (Array original - media)/ (Desviacion Tipica). Se usa np.mean y np.td sobre el axis 0 para tener 
#la operacion por cada feature(columna en este caso)

data_mean = np.mean(data, axis = 0)
data_std = np.std(data, axis = 0)
data_final = (data - data_mean)/data_std
data_final

array([[ 0.90519211, -0.13841641,  0.72839007],
       [ 0.22348541,  0.23943015,  0.63459985],
       [-0.2098285 ,  0.35464955, -0.62771253],
       ...,
       [-0.11434894, -1.07860972,  0.10755077],
       [-0.95632675, -1.40785038, -1.10449649],
       [ 0.87142279, -0.16883564,  0.48355621]])

b) Imaginemos ahora que el array 2d tiene una fila por cada feature y una columna por cada medición (la transpuesta de la matriz anterior). ¿Cómo vectorizamos la operación ahora? (réstale la media por fila y divide por la desviación típica por fila).

In [6]:
data = np.random.normal(loc=[-10, 0, 10], scale=[2, 1, 2], size=(1000,3)).T
data.shape

(3, 1000)

In [7]:
# YOUR CODE HERE

data_mean = np.mean(data, axis = 1)
data_std = np.std(data, axis = 1)

#Se realiza la misma operación ue en la primera parte del ejercicio. Sin embargo, en este caso las operaciones mean
#y std de np devuelven un array de 1D con 3 elementos, ya que es un resultado por operación a lo largo de las filas.

#Para poder operar con el array original de shape (3,1000), es necesario añadir otra dimension a los resultados, 
#usando newaxis; conn un nuevo eje de la misma dimensión que el eje original

data_mean = data_mean[np.newaxis, :]
data_mean = data_mean.T
data_std = data_std[np.newaxis, :]
data_std = data_std.T

data_final = (data - data_mean)/data_std
data_final

array([[ 0.76360885,  0.30683858,  1.19406471, ...,  0.76981071,
        -1.37924247, -0.05921331],
       [-2.01837731, -2.16805534, -0.17516458, ..., -0.2415991 ,
        -0.24621049,  0.32441647],
       [-0.69557627,  1.91478166, -1.57563397, ...,  1.04899544,
        -1.29259168,  0.4438341 ]])

## Sistemas de coordenadas - Vectorización (0.7p)

Vamos a escribir funciones para convertir puntos dados en un sistema de coordenadas cartesianas a los mismos puntos expresados en un sistema de coordenadas polares.

<img src="coordinates.png" style="height: 200px;float: left">

Dado un punto en coordenadas cartesianas $(x,y)$, sus correspondientes coordenadas polares $(r, \varphi)$ se obtienen como sigue:

\begin{equation}
r = \sqrt{(x^2+y^2)}
\end{equation}
\begin{equation}
\varphi = arctan\left(\frac{y}{x}\right)
\end{equation}

<div style="clear: left"/>

* Escribe una función usando NumPy y otra basada en Python puro tal que, dado un array o lista, respectivamente, de coordenadas cartesianas, devuelva un array o lista de coordenadas polares. 
* Compara su rendimiento (hint: magic commands de Jupyter notebook)



In [8]:
#Se crean los elementos de coordenadas cartesianas en forma de array y listas
import random
import math
num_muestras_input = 10000
Z_cartesian = np.random.random((num_muestras_input,2))


list_x = [random.random() for num in range(0, num_muestras_input)]
list_y = [random.random() for num in range(0, num_muestras_input)]

Z_cartesian

array([[0.33023089, 0.70821221],
       [0.83387874, 0.67921803],
       [0.63538473, 0.83256848],
       ...,
       [0.5052063 , 0.54523935],
       [0.27498161, 0.51259994],
       [0.03377732, 0.10598399]])

In [9]:
# Dos funciones diferentes con numpy primero y con Python tradicional después.

def cart_to_polar_np(array_cart):
    #se realizan las operaciones primero para sacar el módulo del vector, con la función sum sobre el 
    #cuadrado de cada elemento por fila
    array_r = np.sum(np.square(array_cart), axis=1)
    array_r = np.sqrt(array_r)
    #El ángulo se obtiene diviiendo los elementos y entre los x  con la arctan de ese resultado
    array_angle = np.divide(array_cart[:,1], array_cart[:,0])
    array_angle = np.arctan(array_angle)
    #para representar ambos cálculos, r y angle, en la misma matriz se tiene que concatenar. al ser elementos de
    #una sola dimensión, se añade otra y se trasponen para representar el resultado final como un array cuyas
    #columnas son el vector y el ángulo correspondiente con los índices del array cartesiano original
    array_r = array_r[np.newaxis, :]
    array_r = array_r.T
    array_angle = array_angle[np.newaxis, :]
    array_angle = array_angle.T

    final = np.concatenate((array_r, array_angle), axis=1)
    return final

def cart_to_polar_list(x, y):
    
    r = []
    angle =[]
    #se usa un bucle que recorre las dos listas de manera paralela y se opera cada elemento de las mismas;
    #añadiendo el resultado a las listas resultado que representan el módulo del vector (r), y el ángulo
    for numx, numy in zip(x, y):
        r.append(math.sqrt((numx**2) + (numy**2)))
        angle.append(math.atan(numy/numx))
        
    return r, angle
        

In [10]:
%time polar_array = cart_to_polar_np(Z_cartesian)

CPU times: user 3.81 ms, sys: 1.73 ms, total: 5.53 ms
Wall time: 3.66 ms


In [11]:
%time (r, angle) = cart_to_polar_list(list_x, list_y)

CPU times: user 13.8 ms, sys: 908 µs, total: 14.7 ms
Wall time: 7.46 ms


Se puede observar con la función time que la operación con numpy es más eficiente en cuanto a procesamiento y tiempo 
de ejecución